from __future__ import annotations

from AEGIS.server.services.llm.prompts import AGENT_EXTRACTION_PROMPT, AGENT_RESPONSE_PROMPT

AGENT_INTENT_SYSTEM_PROMPT = AGENT_EXTRACTION_PROMPT
AGENT_CHAT_SYSTEM_PROMPT = AGENT_RESPONSE_PROMPT
