from __future__ import annotations

from AEGIS.server.services.llm.prompts import (
    AGENT_DECISION_SYSTEM_PROMPT,
    CHAT_RESPONSE_SYSTEM_PROMPT,
    PARSER_MODEL_SYSTEM_PROMPT,
)

AGENT_INTENT_SYSTEM_PROMPT = PARSER_MODEL_SYSTEM_PROMPT
AGENT_DECISION_PROMPT = AGENT_DECISION_SYSTEM_PROMPT
AGENT_CHAT_SYSTEM_PROMPT = CHAT_RESPONSE_SYSTEM_PROMPT
